import type { Metadata } from "next";
import "./globals.css";
import { Body } from "./Body";
import { Registry } from "./Registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Registry>
      <html lang="en">
        <Body>{children}</Body>
      </html>
    </Registry>
  );
}
